### ISSUE TITLE
项目还有人维护吗？

### ISSUE THREAD

**Issue by weiyu10** [xiaoluoge11/lmanager#6]
这个项目还有人维护吗？好像七八个月都没有更新过了

**Comment by xiaoluoge11** [comment]
你好，这个项目目前人手有限，暂时不维护，，目前在写新项目网谅解

在 2016-05-24 08:57:25，"weiyu" notifications@github.com 写道：

这个项目还有人维护吗？好像七八个月都没有更新过了

**Comment by weiyu10** [comment]
将来还会继续维护吗？我觉得这个idea很好啊

**Comment by xiaoluoge11** [comment]
你好感谢支持，，既然这样，我们这边过段时间应该会出第二个页面改观的版本，还有很多功能会完善很多

在 2016-05-24 09:04:08，"weiyu" notifications@github.com 写道：

将来还会继续维护吗？我觉得这个idea很好啊

**Comment by weiyu10** [comment]
期待新版

**Comment by xiaoluoge11** [comment]
谢谢支持

在 2016-05-24 09:10:06，"weiyu" notifications@github.com 写道：

期待新版
